import { Recipe, WeeklyMealPlan, PantryItem, UserPreferences, GroceryItem, Family, UserSession } from "@/types";

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "rec-1",
    title: "Pasta Integral amb Pesto de Carbassó i Nous",
    description: "Un primer plat cremós, lleuger i ric en greixos saludables, a punt en només 15 minuts.",
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    calories: 480,
    nutrition: { calories: 480, protein: 16, carbs: 64, fat: 18, fiber: 7 },
    tags: ["Primers", "Ràpid", "Vegetarià", "Saludable"],
    dietaryTags: ["vegetarian", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-1", name: "Pasta integral (plomes o espirals)", amount: 160, unit: "g", category: "pantry" },
      { id: "ing-2", name: "Carbassons frescos", amount: 2, unit: "unitats", category: "produce" },
      { id: "ing-3", name: "Nous pelades del país", amount: 30, unit: "g", category: "pantry" },
      { id: "ing-4", name: "Formatge Parmesà ratllat", amount: 25, unit: "g", category: "dairy" },
      { id: "ing-5", name: "Oli d'oliva verge extra", amount: 15, unit: "ml", category: "pantry" },
      { id: "ing-6", name: "Fulles d'alfàbrega fresca", amount: 8, unit: "fulles", category: "produce" },
      { id: "ing-7", name: "Gra d'all", amount: 1, unit: "gra", category: "produce" },
    ],
    instructions: [
      "Posa a bullir una olla amb abundant aigua i sal i cou la pasta al dente.",
      "Renta els carbassons, talla'ls a rodanxes i salta'ls 3 minuts a la paella amb un raig d'oli i el gra d'all.",
      "Tritura els carbassons amb les nous, el formatge parmesà, l'alfàbrega i un cullerot d'aigua de cocció de la pasta.",
      "Escorre la pasta i barreja-la amb el pesto de carbassó fora del foc. Serveix amb nous picades per sobre.",
    ],
  },
  {
    id: "rec-2",
    title: "Salmó al Forn amb Espàrrecs Verds i Llimona",
    description: "Filet de salmó sucós i daurat rostit amb herbes aromàtiques i espàrrecs cruixents.",
    prepTimeMinutes: 8,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 520,
    nutrition: { calories: 520, protein: 42, carbs: 8, fat: 34, fiber: 4 },
    tags: ["Segons", "Peix", "Low-Carb", "Keto", "Alt en Proteïna"],
    dietaryTags: ["pescatarian", "keto", "low-carb", "gluten-free", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-8", name: "Filets de salmó fresc", amount: 350, unit: "g", category: "meat" },
      { id: "ing-9", name: "Espàrrecs verds frescos", amount: 300, unit: "g", category: "produce" },
      { id: "ing-10", name: "Llimona ecològica", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-11", name: "Oli d'oliva verge extra", amount: 15, unit: "ml", category: "pantry" },
      { id: "ing-12", name: "Anet o farigola fresca", amount: 1, unit: "branqueta", category: "produce" },
      { id: "ing-13", name: "Sal marina i pebre negre", amount: 1, unit: "pessic", category: "pantry" },
    ],
    instructions: [
      "Escalfa el forn a 190°C.",
      "Neteja els espàrrecs traient la part llenyosa i col·loca'ls en una safata amb paper de forn.",
      "Col·loca els filets de salmó al costat dels espàrrecs, amaneix amb oli, suc de mitja llimona, sal, pebre i herbes.",
      "Posa rodanxes de llimona sobre el salmó i enforna durant 14-16 minuts fins que estigui al punt.",
    ],
  },
  {
    id: "rec-3",
    title: "Bowl Proteic amb Pollastre a la Planxa, Quinoa i Alvocat",
    description: "Plat únic complet, colorit i energètic, ideal també per emportar com a carmanyola a la feina.",
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 560,
    nutrition: { calories: 560, protein: 46, carbs: 52, fat: 20, fiber: 9 },
    tags: ["Plat Únic", "Fitness", "Meal Prep", "Alt en Proteïna"],
    dietaryTags: ["gluten-free", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-14", name: "Pit de pollastre de pagès", amount: 300, unit: "g", category: "meat" },
      { id: "ing-15", name: "Quinoa", amount: 120, unit: "g", category: "pantry" },
      { id: "ing-16", name: "Alvocat madur", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-17", name: "Tomàquets cirerols (cherry)", amount: 150, unit: "g", category: "produce" },
      { id: "ing-18", name: "Espinacs baby frescos", amount: 80, unit: "g", category: "produce" },
      { id: "ing-19", name: "Llima o llimona", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-20", name: "Llavors de sèsam torrat", amount: 10, unit: "g", category: "pantry" },
    ],
    instructions: [
      "Esbandeix la quinoa i cou-la en 240ml d'aigua amb un pessic de sal durant 12 minuts; deixa-la refredar.",
      "Fes el pit de pollastre a la planxa amb espècies (pebre vermell dolç, orenga, sal) 4-5 minuts per banda i talla'l a tires.",
      "Talla l'alvocat a daus i els tomàquets cirerols per la meitat.",
      "Munta els bols amb una base d'espinacs i quinoa, afegeix el pollastre, l'alvocat, els tomàquets i acaba amb sèsam i suc de llima.",
    ],
  },
  {
    id: "rec-4",
    title: "Porridge Cremós de Civada amb Fruits del Bosc i Mantega de Cacauet",
    description: "L'esmorzar ideal per començar el dia amb energia d'alliberament lent i màxima sacietat.",
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 380,
    nutrition: { calories: 380, protein: 14, carbs: 54, fat: 12, fiber: 8 },
    tags: ["Esmorzar", "Dolç Saludable", "Ràpid", "Vegetarià"],
    dietaryTags: ["vegetarian", "vegan", "dairy-free"],
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-21", name: "Flocs de civada integrals", amount: 50, unit: "g", category: "pantry" },
      { id: "ing-22", name: "Beguda de civada o ametlla", amount: 180, unit: "ml", category: "dairy" },
      { id: "ing-23", name: "Nabius o gerds frescos", amount: 60, unit: "g", category: "produce" },
      { id: "ing-24", name: "Mantega de cacauet 100%", amount: 15, unit: "g", category: "pantry" },
      { id: "ing-25", name: "Canyella de Ceilan en pols", amount: 1, unit: "pessic", category: "pantry" },
      { id: "ing-26", name: "Mel pura o xarop d'atzavara", amount: 10, unit: "ml", category: "pantry" },
    ],
    instructions: [
      "En un cassó petit, aboca els flocs de civada amb la beguda vegetal i un pessic de canyella.",
      "Cou a foc mitjà remenant sense parar durant 4-5 minuts fins a obtenir una textura espessa i cremosa.",
      "Serveix en un bol i decora amb fruits del bosc frescos, una cullerada de mantega de cacauet i un fil de mel.",
    ],
  },
  {
    id: "rec-5",
    title: "Truita Esponjosa d'Espinacs, Mató Fresc i Cúrcuma",
    description: "Sopar ràpid, nutritiu i lleuger, molt ric en proteïna d'alt valor biològic i ferro.",
    prepTimeMinutes: 7,
    cookTimeMinutes: 10,
    servings: 2,
    calories: 320,
    nutrition: { calories: 320, protein: 24, carbs: 5, fat: 22, fiber: 3 },
    tags: ["Segons", "Ous", "Vegetarià", "Low-Carb", "Keto"],
    dietaryTags: ["vegetarian", "keto", "low-carb", "gluten-free", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-27", name: "Ous frescos ecològics", amount: 4, unit: "ous", category: "dairy" },
      { id: "ing-28", name: "Mató fresc de llet de vaca", amount: 100, unit: "g", category: "dairy" },
      { id: "ing-29", name: "Espinacs frescos de fulla tendra", amount: 150, unit: "g", category: "produce" },
      { id: "ing-30", name: "Oli d'oliva verge extra", amount: 10, unit: "ml", category: "pantry" },
      { id: "ing-31", name: "Cúrcuma en pols", amount: 1, unit: "culleradeta", category: "pantry" },
      { id: "ing-32", name: "Sal marina i nou moscada", amount: 1, unit: "pessic", category: "pantry" },
    ],
    instructions: [
      "Salteja els espinacs en una paella antiadherent durant 2 minuts amb una mica d'oli i escorre'ls bé.",
      "En un bol bat els ous amb un pessic de sal, cúrcuma i una mica de nou moscada.",
      "Afegeix els espinacs i cullerades de mató fresc sense remenar excessivament.",
      "Cuina a la paella tapada a foc suau durant 6-8 minuts, tombant-la a mitja cocció fins que qualli.",
    ],
  },
  {
    id: "rec-6",
    title: "Curri Cremós de Cigrons i Llet de Coco amb Arròs Basmati",
    description: "Plat vegà calent, especiat i reconfortant, perfumat amb gingebre fresc i coriandre.",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    calories: 510,
    nutrition: { calories: 510, protein: 15, carbs: 70, fat: 19, fiber: 11 },
    tags: ["Primers", "Plat Únic", "Vegà", "Especiat", "Confort Food"],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-33", name: "Cigrons cuits de pot", amount: 400, unit: "g", category: "pantry" },
      { id: "ing-34", name: "Llet de coco en llauna", amount: 250, unit: "ml", category: "pantry" },
      { id: "ing-35", name: "Tomàquet triturat natural", amount: 150, unit: "g", category: "pantry" },
      { id: "ing-36", name: "Arròs Basmati aromàtic", amount: 180, unit: "g", category: "pantry" },
      { id: "ing-37", name: "Ceba de Figueres", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-38", name: "Curri dolç i Garam Masala", amount: 2, unit: "cullerades", category: "pantry" },
      { id: "ing-39", name: "Gingebre fresc ratllat", amount: 10, unit: "g", category: "produce" },
    ],
    instructions: [
      "Cou l'arròs basmati en aigua bullent amb sal durant 10-12 minuts fins que quedi solt.",
      "En una cassola, sofregeix la ceba i el gingebre picats amb les espècies durant 2 minuts.",
      "Afegeix el tomàquet, els cigrons esbandits i la llet de coco. Deixa fer xup-xup durant 15 minuts a foc lent.",
      "Serveix el curri ben calent sobre una base d'arròs basmati amb coriandre o julivert picat per sobre.",
    ],
  },
  {
    id: "rec-7",
    title: "Torrada d'Alvocat amb Ou Poché i Llavors de Chia",
    description: "Un gran clàssic per al brunch o per a un esmorzar salat i ric en nutrients de màxima qualitat.",
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 340,
    nutrition: { calories: 340, protein: 15, carbs: 28, fat: 19, fiber: 6 },
    tags: ["Esmorzar", "Brunch", "Ràpid", "Vegetarià"],
    dietaryTags: ["vegetarian", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-40", name: "Pa de sègol o de massa mare", amount: 2, unit: "llesques", category: "bakery" },
      { id: "ing-41", name: "Alvocat madur", amount: 0.5, unit: "unitat", category: "produce" },
      { id: "ing-42", name: "Ou fresc ecològic", amount: 1, unit: "ou", category: "dairy" },
      { id: "ing-43", name: "Flocs de bitxo (chili flakes)", amount: 1, unit: "pessic", category: "pantry" },
      { id: "ing-44", name: "Llavors de chia o sèsam", amount: 5, unit: "g", category: "pantry" },
      { id: "ing-45", name: "Suc de llimona", amount: 5, unit: "ml", category: "produce" },
    ],
    instructions: [
      "Torra les llesques de pa fins que estiguin ben daurades i cruixents.",
      "Aixafeu l'alvocat amb una forquilla juntament amb unes gotes de llimona, sal i pebre.",
      "Fes l'ou poché en aigua calenta amb una cullerada de vinagre durant 3 minuts, deixant el rovell líquid.",
      "Unta l'alvocat a la torrada, col·loca l'ou poché a sobre i empolsa amb llavors de chia i bitxo.",
    ],
  },
  {
    id: "rec-8",
    title: "Filet d'Orada amb Tomàquets Cherry i Olives Negres",
    description: "Cocció tradicional mediterrània que ressalta la frescor i el sabor autèntic del peix fresc.",
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 2,
    calories: 310,
    nutrition: { calories: 310, protein: 38, carbs: 6, fat: 14, fiber: 2 },
    tags: ["Segons", "Peix", "Mediterrani", "Tradició", "Lleuger"],
    dietaryTags: ["pescatarian", "mediterranean", "gluten-free", "low-carb"],
    imageUrl: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "medium",
    ingredients: [
      { id: "ing-46", name: "Filets d'orada fresca", amount: 350, unit: "g", category: "meat" },
      { id: "ing-47", name: "Tomàquets cirerols madurs", amount: 200, unit: "g", category: "produce" },
      { id: "ing-48", name: "Olives negres d'Aragó o Kalamata", amount: 30, unit: "g", category: "pantry" },
      { id: "ing-49", name: "Vi blanc sec", amount: 50, unit: "ml", category: "beverages" },
      { id: "ing-50", name: "Julivert fresc picat", amount: 1, unit: "manat", category: "produce" },
      { id: "ing-51", name: "Gra d'all", amount: 1, unit: "gra", category: "produce" },
    ],
    instructions: [
      "En una paella àmplia escalfa oli d'oliva amb el gra d'all picat i un toc de pebre.",
      "Afegeix els tomàquets tallats per la meitat i les olives, saltant durant 2 minuts.",
      "Afegeix el vi blanc, mig got d'aigua i col·loca els filets d'orada amb la pell cap amunt.",
      "Tapa i cou durant 8-10 minuts a foc mitjà. Serveix amb abundant julivert fresc picat.",
    ],
  },
  {
    id: "rec-9",
    title: "Empedrat Tradicional de Mongetes del Ganxet amb Tonyina",
    description: "Amanida fresca tradicional catalana de llegums, molt rica en fibra i proteïna vegetal i de peix.",
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    calories: 420,
    nutrition: { calories: 420, protein: 32, carbs: 45, fat: 12, fiber: 10 },
    tags: ["Primers", "Plat Únic", "Tradició", "Llegums", "Ràpid"],
    dietaryTags: ["pescatarian", "gluten-free", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    ingredients: [
      { id: "ing-52", name: "Mongetes del Ganxet cuites", amount: 350, unit: "g", category: "pantry" },
      { id: "ing-53", name: "Tonyina en oli d'oliva", amount: 120, unit: "g", category: "pantry" },
      { id: "ing-54", name: "Tomàquet d'amanir madur", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-55", name: "Pebrot verd tendre", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-56", name: "Ceba tendra", amount: 0.5, unit: "unitat", category: "produce" },
      { id: "ing-57", name: "Olives negres mortes", amount: 25, unit: "g", category: "pantry" },
      { id: "ing-58", name: "Oli d'oliva verge extra i vinagre", amount: 20, unit: "ml", category: "pantry" },
    ],
    instructions: [
      "Esbandeix les mongetes cuites i escorre-les amb cura per no trencar-les.",
      "Pica el tomàquet, el pebrot verd i la ceba tendra a daus petits.",
      "En una amanidora, barreja les mongetes amb les verdures picades, la tonyina esmicolada i les olives negres.",
      "Amaneix amb un bon raig d'oli d'oliva verge extra, una mica de vinagre i sal marina. Serveix fresca.",
    ],
  },
  {
    id: "rec-10",
    title: "Crema Suau de Carbassa i Gingebre amb Llavors Torrades",
    description: "Primer plat de cullera càlid, vellutat i molt reconfortant per a les nits de tardor i hivern.",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    calories: 220,
    nutrition: { calories: 220, protein: 6, carbs: 32, fat: 8, fiber: 6 },
    tags: ["Primers", "Sopes i Cremes", "Vegà", "Lleuger", "Saludable"],
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    imageUrl: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=800&q=80",
    source: "curated",
    difficulty: "easy",
    moderationStatus: "approved_public",
    isPublic: true,
    ingredients: [
      { id: "ing-59", name: "Carbassa violí pelada i tallada a daus", amount: 500, unit: "g", category: "produce" },
      { id: "ing-60", name: "Porro", amount: 1, unit: "unitat", category: "produce" },
      { id: "ing-61", name: "Gingebre fresc ratllat", amount: 8, unit: "g", category: "produce" },
      { id: "ing-62", name: "Brou vegetal suau", amount: 400, unit: "ml", category: "pantry" },
      { id: "ing-63", name: "Llavors de carbassa torrades", amount: 15, unit: "g", category: "pantry" },
      { id: "ing-64", name: "Oli d'oliva verge extra", amount: 15, unit: "ml", category: "pantry" },
    ],
    instructions: [
      "En una cassola, ofega el porro a rodanxes amb l'oli d'oliva durant 4 minuts.",
      "Afegeix els daus de carbassa, el gingebre ratllat i el brou vegetal.",
      "Fes bullir a foc mitjà durant 15-18 minuts fins que la carbassa estigui completament tova.",
      "Tritura molt finament amb la batedora fins a obtenir una textura sedosa. Serveix amb les llavors de carbassa per sobre.",
    ],
  },
  {
    id: "rec-pending-1",
    familyId: "fam-pending-1",
    authorName: "Marta Costa (Família Costa)",
    title: "Fideuà de Gandia Tradicional amb Gambes i Allioli",
    description: "Recepta familiar marinera amb fideus torrats i sofregit intens de sípia i gambes.",
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 540,
    nutrition: { calories: 540, protein: 32, carbs: 62, fat: 18, fiber: 5 },
    tags: ["Plat Únic", "Peix", "Tradició", "Mariner"],
    dietaryTags: ["pescatarian", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    source: "custom",
    difficulty: "medium",
    moderationStatus: "pending_review",
    isPublic: false,
    createdAt: "2026-09-05T14:40:00.000Z",
    ingredients: [
      { id: "ing-p1", name: "Fideus del núm. 2 o 3", amount: 350, unit: "g", category: "pantry" },
      { id: "ing-p2", name: "Gambes fresques o llagostins", amount: 8, unit: "unitats", category: "meat" },
      { id: "ing-p3", name: "Sípia neta tallada a daus", amount: 250, unit: "g", category: "meat" },
      { id: "ing-p4", name: "Fumet de peix de roca", amount: 800, unit: "ml", category: "pantry" },
      { id: "ing-p5", name: "Allioli casolà suau", amount: 4, unit: "cullerades", category: "dairy" },
    ],
    instructions: [
      "En una paella amb oli, marca les gambes 1 minut per banda i reserva-les.",
      "Dora la sípia i afegeix un sofregit de ceba, all i tomàquet ratllat.",
      "Dora els fideus a la paella fins que agafin un color avellanat.",
      "Aboca el fumet de peix bullent i cou 8-10 minuts fins que el fideu quedi sec i aixecat.",
      "Serveix amb les gambes a sobre i una cullerada d'allioli casolà.",
    ],
  },
  {
    id: "rec-pending-2",
    familyId: "fam-pending-2",
    authorName: "Oriol Puig (Família Puig & Roca)",
    title: "Escalivada Catalana amb Formatge de Cabra Gratinat",
    description: "Pebrots vermells, albergínies i cebes escalivades a la llenya amb medalló de formatge de cabra.",
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 2,
    calories: 360,
    nutrition: { calories: 360, protein: 14, carbs: 22, fat: 24, fiber: 8 },
    tags: ["Primers", "Vegetarià", "Tradició", "Forno"],
    dietaryTags: ["vegetarian", "gluten-free", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    source: "custom",
    difficulty: "easy",
    moderationStatus: "pending_review",
    isPublic: false,
    createdAt: "2026-09-05T16:15:00.000Z",
    ingredients: [
      { id: "ing-p6", name: "Pebrots vermells grans", amount: 2, unit: "unitats", category: "produce" },
      { id: "ing-p7", name: "Albergínies morades", amount: 2, unit: "unitats", category: "produce" },
      { id: "ing-p8", name: "Formatge de cabra (rulo)", amount: 100, unit: "g", category: "dairy" },
      { id: "ing-p9", name: "Oli d'oliva verge extra", amount: 20, unit: "ml", category: "pantry" },
    ],
    instructions: [
      "Enforna els pebrots i albergínies a 200°C durant 45 minuts fins que estiguin ben tendres.",
      "Pela les verdures i fes-ne tires fines.",
      "Col·loca les tires d'escalivada en una cassoleta, amaneix amb oli i sal.",
      "Posa una rodanxa de formatge de cabra a sobre i gratina 5 minuts al forn.",
    ],
  },
];

export const INITIAL_PANTRY: PantryItem[] = [
  { id: "p-1", name: "Pasta integral (plomes)", amount: 500, unit: "g", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-2", name: "Oli d'oliva verge extra", amount: 750, unit: "ml", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-3", name: "Arròs Basmati aromàtic", amount: 1000, unit: "g", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-4", name: "Cigrons cuits de pot", amount: 2, unit: "pots", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-5", name: "Mongetes del Ganxet cuites", amount: 1, unit: "pot", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-6", name: "Formatge Parmesà ratllat", amount: 200, unit: "g", category: "dairy", expiryDate: "2026-09-25", addedAt: "2026-09-01" },
  { id: "p-7", name: "Ous frescos ecològics", amount: 6, unit: "ous", category: "dairy", expiryDate: "2026-09-15", addedAt: "2026-09-02" },
  { id: "p-8", name: "Flocs de civada integrals", amount: 400, unit: "g", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-9", name: "Carbassons frescos", amount: 3, unit: "unitats", category: "produce", expiryDate: "2026-09-09", isLow: false, addedAt: "2026-09-04" },
  { id: "p-10", name: "Nous pelades del país", amount: 150, unit: "g", category: "pantry", addedAt: "2026-09-01" },
  { id: "p-11", name: "Tonyina en oli d'oliva", amount: 3, unit: "llaunes", category: "pantry", addedAt: "2026-09-01" },
];

export const DEFAULT_PREFERENCES: UserPreferences = {
  fullName: "Xavi (Organitzador)",
  householdSize: 2,
  dietaryPreference: "mediterranean",
  allergies: [],
  dislikedIngredients: [],
  dailyCalorieTarget: 2000,
  macroRatio: { protein: 25, carbs: 50, fat: 25 },
  cookingSkillLevel: "intermediate",
  maxCookingTimeMinutes: 30,
  budgetLevel: "moderate",
};

export const INITIAL_MEAL_PLAN: WeeklyMealPlan = {
  id: "plan-current-week",
  familyId: "fam-main",
  title: "Menú Setmanal Equilibrat de la Família",
  weekStartDate: "2026-09-07",
  householdSize: 2,
  targetDailyCalories: 2000,
  dietaryPreference: "mediterranean",
  createdAt: "2026-09-05T18:00:00.000Z",
  updatedAt: "2026-09-05T18:00:00.000Z",
  slots: [
    // Dilluns
    { id: "s-mon-b", day: "monday", mealType: "breakfast", recipeId: "rec-4", recipe: INITIAL_RECIPES[3] },
    { id: "s-mon-l", day: "monday", mealType: "lunch", recipeId: "rec-1", recipe: INITIAL_RECIPES[0] },
    { id: "s-mon-d", day: "monday", mealType: "dinner", recipeId: "rec-2", recipe: INITIAL_RECIPES[1] },
    // Dimarts
    { id: "s-tue-b", day: "tuesday", mealType: "breakfast", recipeId: "rec-7", recipe: INITIAL_RECIPES[6] },
    { id: "s-tue-l", day: "tuesday", mealType: "lunch", recipeId: "rec-3", recipe: INITIAL_RECIPES[2] },
    { id: "s-tue-d", day: "tuesday", mealType: "dinner", recipeId: "rec-5", recipe: INITIAL_RECIPES[4] },
    // Dimecres
    { id: "s-wed-b", day: "wednesday", mealType: "breakfast", recipeId: "rec-4", recipe: INITIAL_RECIPES[3] },
    { id: "s-wed-l", day: "wednesday", mealType: "lunch", recipeId: "rec-9", recipe: INITIAL_RECIPES[8] },
    { id: "s-wed-d", day: "wednesday", mealType: "dinner", recipeId: "rec-8", recipe: INITIAL_RECIPES[7] },
    // Dijous
    { id: "s-thu-b", day: "thursday", mealType: "breakfast", recipeId: "rec-7", recipe: INITIAL_RECIPES[6] },
    { id: "s-thu-l", day: "thursday", mealType: "lunch", recipeId: "rec-6", recipe: INITIAL_RECIPES[5] },
    { id: "s-thu-d", day: "thursday", mealType: "dinner", recipeId: "rec-10", recipe: INITIAL_RECIPES[9] },
    // Divendres
    { id: "s-fri-b", day: "friday", mealType: "breakfast", recipeId: "rec-4", recipe: INITIAL_RECIPES[3] },
    { id: "s-fri-l", day: "friday", mealType: "lunch", recipeId: "rec-1", recipe: INITIAL_RECIPES[0] },
    { id: "s-fri-d", day: "friday", mealType: "dinner", recipeId: "rec-2", recipe: INITIAL_RECIPES[1] },
    // Dissabte
    { id: "s-sat-b", day: "saturday", mealType: "breakfast", recipeId: "rec-7", recipe: INITIAL_RECIPES[6] },
    { id: "s-sat-l", day: "saturday", mealType: "lunch", recipeId: "rec-5", recipe: INITIAL_RECIPES[4] },
    { id: "s-sat-d", day: "saturday", mealType: "dinner", recipeId: "rec-8", recipe: INITIAL_RECIPES[7] },
    // Diumenge
    { id: "s-sun-b", day: "sunday", mealType: "breakfast", recipeId: "rec-4", recipe: INITIAL_RECIPES[3] },
    { id: "s-sun-l", day: "sunday", mealType: "lunch", recipeId: "rec-3", recipe: INITIAL_RECIPES[2] },
    { id: "s-sun-d", day: "sunday", mealType: "dinner", recipeId: "rec-9", recipe: INITIAL_RECIPES[8] },
  ],
};

export const DEFAULT_FAMILY: Family = {
  id: "fam-main",
  name: "Família MenúPlanik",
  code: "FAM-7492",
  organizerName: "Xavi",
  organizerEmail: "xavi@menuplanik.cat",
  adminId: "usr-admin-1",
  status: "approved",
  createdAt: "2026-09-01T00:00:00.000Z",
  approvedAt: "2026-09-01T00:00:00.000Z",
  approvedBy: "super-admin",
  members: [
    {
      id: "m-1",
      familyId: "fam-main",
      userId: "usr-admin-1",
      name: "Xavi",
      email: "xavi@menuplanik.cat",
      role: "admin",
      joinedAt: "2026-09-01T00:00:00.000Z",
      color: "#16a34a",
    },
    {
      id: "m-2",
      familyId: "fam-main",
      userId: "usr-user-1",
      name: "Júlia",
      email: "julia@menuplanik.cat",
      role: "user",
      joinedAt: "2026-09-02T10:30:00.000Z",
      color: "#0284c7",
    },
  ],
};

export const INITIAL_FAMILIES: Family[] = [
  DEFAULT_FAMILY,
  {
    id: "fam-pending-1",
    name: "Família Costa",
    code: "FAM-3912",
    organizerName: "Marta Costa",
    organizerEmail: "marta.costa@exemple.cat",
    adminId: "usr-admin-2",
    status: "pending",
    createdAt: "2026-09-05T14:30:00.000Z",
    members: [
      {
        id: "m-costa-1",
        familyId: "fam-pending-1",
        userId: "usr-admin-2",
        name: "Marta Costa",
        email: "marta.costa@exemple.cat",
        role: "admin",
        joinedAt: "2026-09-05T14:30:00.000Z",
        color: "#8b5cf6",
      },
    ],
  },
  {
    id: "fam-pending-2",
    name: "Família Puig & Roca",
    code: "FAM-8821",
    organizerName: "Oriol Puig",
    organizerEmail: "oriol.puig@exemple.cat",
    adminId: "usr-admin-3",
    status: "pending",
    createdAt: "2026-09-05T16:00:00.000Z",
    members: [
      {
        id: "m-puig-1",
        familyId: "fam-pending-2",
        userId: "usr-admin-3",
        name: "Oriol Puig",
        email: "oriol.puig@exemple.cat",
        role: "admin",
        joinedAt: "2026-09-05T16:00:00.000Z",
        color: "#f59e0b",
      },
    ],
  },
];

export const DEFAULT_SESSION: UserSession = {
  userId: "",
  memberId: "",
  familyId: "",
  name: "Convidat",
  email: "",
  role: "user",
  status: "pending",
  familyCode: "",
  familyName: "",
  isAuthenticated: false,
};

export const SUPERUSER_SESSION: UserSession = {
  userId: "super-admin-uid",
  memberId: "super-admin",
  familyId: "",
  name: "Superadministrador",
  email: "admin@menuplanik.cat",
  role: "superadmin",
  status: "active",
  familyCode: "ADMIN",
  familyName: "Panell Global",
  isAuthenticated: true,
};

export const USER_SESSION: UserSession = {
  userId: "usr-user-1",
  memberId: "m-2",
  familyId: "fam-main",
  name: "Júlia",
  email: "julia@menuplanik.cat",
  role: "user",
  status: "active",
  familyCode: "FAM-7492",
  familyName: "Família MenúPlanik",
  isAuthenticated: true,
};

export function generateGroceriesFromPlan(plan: WeeklyMealPlan, pantry: PantryItem[] = []): GroceryItem[] {
  const map: Record<string, GroceryItem> = {};

  plan.slots.forEach((slot) => {
    if (!slot.recipe) return;
    slot.recipe.ingredients.forEach((ing) => {
      const key = `${ing.name.toLowerCase()}-${ing.unit.toLowerCase()}`;
      const amountForHousehold = (ing.amount / (slot.recipe?.servings || 1)) * plan.householdSize;

      if (!map[key]) {
        const inPantryItem = pantry.find((p) => p.name.toLowerCase().includes(ing.name.toLowerCase()) || ing.name.toLowerCase().includes(p.name.toLowerCase()));
        map[key] = {
          id: `groc-${Math.random().toString(36).substring(2, 9)}`,
          name: ing.name,
          amount: Math.round(amountForHousehold * 10) / 10,
          unit: ing.unit,
          category: ing.category || "other",
          checked: false,
          mealPlanId: plan.id,
          recipeSource: slot.recipe?.title,
          inPantry: !!inPantryItem,
        };
      } else {
        map[key].amount = Math.round((map[key].amount + amountForHousehold) * 10) / 10;
      }
    });
  });

  return Object.values(map);
}
